/**:
  ros__parameters:
    min_longitudinal_offset: 0.5
    max_longitudinal_offset: 1.0
    min_lateral_offset: -0.5
    max_lateral_offset: 0.5
    min_height_offset: 0.8
    max_height_offset: 1.0
